### PR TITLE
Add the EditorConfig logo in SVG format

### LINKED ISSUE #438: editorconfig logotype in SVG?
Can you please make your logo available in SVG format?

TIA

### PR DESCRIPTION
**Pull request by ffes**
As described in #438 there was a SVG line drawing of the EditorConfig logo uploaded to #291. This PR adds that files to this repo so it can be found more easily by others as well.

It is that file uploaded my @jedmao, but with the line endings converted as set in `.editorconfig`.

Closes #438

### CODE REVIEW

**Review by xuhdev — COMMENTED** [review]
Thanks! Would you mind adding to `.gitattributes`

```
*.svg binary
```

? svg is text but is really treated as a binary file.

**Review by jedmao — APPROVED** [review]

**Comment by ffes** [comment]
@xuhdev What is you reasoning for that? I looked at various discussion on marking SVG as binary files, but different projects have different options on this.

**Comment by xuhdev** [comment]
@ffes When you run `git diff`, the change in the svg files doesn't really make much sense. All we want to know is that the file has changed. It helps clean up these kind of `diff` views, especially when in the future we go back and try to figure out what has changed

**Comment by ffes** [comment]
Fine with me. I don't have a strong opinion on this. Was just curious about your reasoning.

**Comment by xuhdev** [comment]
Yeah, it's just treating `svg` files like other image files and make the git-diff related logs cleaner. It's not super important but when it starts disturbing some functionalities like searching history, it comes pretty handy.

**Pull request merged**
